sudo: required

services:
    - docker

before_script:
    - touch docker/env
    - docker-compose run --rm composer install -n --ignore-platform-reqs
    - docker-compose build php

script:
    - docker-compose run --rm php make tests
