version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./docker/nginx/:/etc/nginx/conf.d/
            - ./public:/var/www/app/public/
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        depends_on:
            - postgres
        volumes:
            - ./:/var/www/app/:rw
        working_dir: /var/www/app/
        environment:
            - SYMFONY_ENV=dev
            - PGHOST=postgres
            - DATABASE_URL=postgres://postgres:postgres@postgres:5432/techmeetups
        env_file:
            - ./docker/env

    node:
        build: ./docker/node
        volumes:
            - ./:/usr/src/client:rw

    postgres:
        image: postgres:latest
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data:rw
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=techmeetups

    pgadmin4:
        image: fenglc/pgadmin4:latest
        depends_on:
            - postgres
        ports:
            - "5050:5050"
        environment:
            - DEFAULT_USER=admin
            - DEFAULT_PASSWORD=password

volumes:
    postgres-data: {}
