framework:
    secret: 'S0ME_SECRET'
    default_locale: fr
    translator:
        paths:
            - '%kernel.project_dir%/src/Infrastructure/Symfony/Resources/translations'
    templating:
        engines: ['twig']
    serializer: { enabled: true }
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
    php_errors:
        log: true

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        '%kernel.project_dir%/src/UI/templates': '__main__'
    date:
        timezone: 'Europe/Paris'

nelmio_cors:
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'PATCH']
            max_age: 3600

services:
    # Autowiring
    # --------------------------------------------------------------------------
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Application\:
        resource: '%kernel.project_dir%/src/Application/*'
    Application\EventSynchronizer:
        public: true
    Domain\:
        resource: '%kernel.project_dir%/src/Domain/*'
    Infrastructure\:
        resource: '%kernel.project_dir%/src/Infrastructure/*'
        exclude: '%kernel.project_dir%/src/Infrastructure/{Persistence/InMemory,ReadModel/InMemory}'
    Infrastructure\Rest\:
        resource: '%kernel.project_dir%/src/Infrastructure/Rest/*'
        tags: ['controller.service_arguments']
    UI\:
        resource: '%kernel.project_dir%/src/UI/*'
        tags: ['controller.service_arguments']

    DbalSchema\:
        resource: '%kernel.project_dir%/vendor/mnapoli/dbal-schema/src/*'
        public: true

    Twig_Extensions_Extension_Intl:
        class: Twig_Extensions_Extension_Intl
    Twig_Extensions_Extension_Date:
        class: Twig_Extensions_Extension_Date

    # Factories
    # --------------------------------------------------------------------------
    Doctrine\DBAL\Connection:
        class: Doctrine\DBAL\Connection
        factory: ['Doctrine\DBAL\DriverManager', getConnection]
        arguments:
            -
                url: "%env(DATABASE_URL)%"
                driver: 'pdo_pgsql'
        public: true

    Domain\Model\City\Cities:
        class: Domain\Model\City\Cities
        factory: ['Infrastructure\Symfony\Factory\CitiesFactory', create]
        arguments: ['%app.techmeetups.cities%']
        public: true

    Meetup\Meetup:
        class: Meetup\Meetup
        factory: ['Meetup\MeetupApiKeyFactory', create]
        arguments: ['%env(MEETUP_API_KEY)%', '@logger']

    # Interfaces
    # --------------------------------------------------------------------------
    Application\EventProvider: '@Infrastructure\Api\Meetup\EventProvider'
    Domain\Model\Event\EventRepository: '@Infrastructure\Persistence\Doctrine\DbalEventRepository'
    Domain\Model\Event\GroupRepository: '@Infrastructure\Persistence\Doctrine\DbalGroupRepository'
    Domain\ReadModel\EventFinder: '@Infrastructure\ReadModel\Doctrine\DbalEventFinder'
    Domain\ReadModel\GroupFinder: '@Infrastructure\ReadModel\Doctrine\DbalGroupFinder'
    Domain\ReadModel\StatsGenerator: '@Infrastructure\ReadModel\Doctrine\DbalStatsGenerator'
    DbalSchema\SchemaDefinition: '@Infrastructure\Persistence\Doctrine\SchemaDefinition'
