homepage:
    path:     /
    defaults: { _controller: UI\Action\Homepage }

groups:
    path:     /groups
    defaults: { _controller: UI\Action\Groups }

stats:
    path:     /stats
    defaults: { _controller: UI\Action\Stats }

feed_mtp:
    path:     /montpellier.{_format}
    defaults: { _controller: UI\Action\Feed }
    requirements:
        _format: atom|rss

ical_mtp:
    path:     /montpellier.ical
    defaults: { _controller: UI\Action\ICal }
